# Generated by Django 3.2.7 on 2021-10-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_user_type'),
        ('labtest', '0002_alter_labtest_medical_centre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0003_alter_package_medical_center'),
        ('medicalcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=200)),
                ('time_slot', models.CharField(max_length=100)),
                ('date_slot', models.CharField(max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.addresslist')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointmentinfo.appointment')),
                ('labtest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtest_info', to='labtest.labtest')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='medicalcenter.medicalcentre')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to='package.package')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPatientListInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appnt_detail', to='appointmentinfo.appointmentdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
