# Generated by Django 3.2.7 on 2021-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentinfo', '0003_alter_appointment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
