# Generated by Django 3.2.7 on 2021-10-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0008_initial'),
        ('appointmentinfo', '0004_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slotID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timeslot.nurseslot'),
        ),
    ]
