# Generated by Django 3.2.7 on 2021-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slotDate',
            field=models.ManyToManyField(to='timeslot.SlotDate'),
        ),
    ]
