# Generated by Django 3.2.7 on 2021-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_auto_20210929_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slotDate',
        ),
        migrations.AddField(
            model_name='slotdate',
            name='slot',
            field=models.ManyToManyField(to='timeslot.TimeSlot'),
        ),
    ]
