# Generated by Django 3.2.7 on 2021-09-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0003_auto_20210929_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotDate',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
