# Generated by Django 3.2.7 on 2021-09-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
        ('timeslot', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseslot',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse'),
        ),
    ]
