# Generated by Django 3.2.7 on 2021-09-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0006_alter_nurseslot_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdate',
            name='slot',
        ),
        migrations.DeleteModel(
            name='NurseSlot',
        ),
        migrations.DeleteModel(
            name='SlotDate',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
