# Generated by Django 3.2.7 on 2021-09-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurse', '0001_initial'),
        ('timeslot', '0007_auto_20210929_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot', models.ManyToManyField(through='timeslot.NurseSlot', to='timeslot.TimeSlot')),
            ],
        ),
        migrations.AddField(
            model_name='nurseslot',
            name='date_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslot.slotdate'),
        ),
        migrations.AddField(
            model_name='nurseslot',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse'),
        ),
        migrations.AddField(
            model_name='nurseslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslot.timeslot'),
        ),
    ]
