# Generated by Django 3.2.7 on 2021-09-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('overview', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='medicalcenter.medicalcentre')),
            ],
        ),
    ]
