# Generated by Django 3.2.7 on 2021-09-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcenter', '0001_initial'),
        ('package', '0002_packagedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='medical_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='medicalcenter.medicalcentre'),
        ),
    ]
