# Generated by Django 3.2.7 on 2021-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Nurse'), (2, 'Runner'), (3, 'User')], default=3),
        ),
    ]
