# Generated by Django 3.2.7 on 2021-10-25 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_setup', models.BooleanField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('setup_type', models.ManyToManyField(to='comunity.DeviceType')),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comunity.society')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityActivityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_steps', models.IntegerField()),
                ('completed_steps', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('community_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunity.communityuserinfo')),
            ],
        ),
    ]
