# Generated by Django 3.2.7 on 2021-10-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuserinfo',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunity.society'),
        ),
    ]
