# Generated by Django 3.2.7 on 2022-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0002_alter_communityuserinfo_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuserinfo',
            name='default_steps',
            field=models.IntegerField(default=5000),
        ),
    ]
