# Generated by Django 3.2.7 on 2022-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0003_communityuserinfo_default_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuserinfo',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
