# Generated by Django 3.2.7 on 2022-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0004_communityuserinfo_device_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('communityUser', models.ManyToManyField(to='comunity.CommunityUserInfo')),
            ],
        ),
    ]
