# Generated by Django 3.2.7 on 2022-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0005_communitygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygroup',
            name='communityUser',
        ),
        migrations.CreateModel(
            name='CommunityGroupUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('communityUser', models.ManyToManyField(to='comunity.CommunityUserInfo')),
                ('groupInfo', models.ManyToManyField(to='comunity.CommunityGroup')),
            ],
        ),
    ]
