# Generated by Django 3.2.7 on 2022-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0006_auto_20220128_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='communityUser',
            field=models.ManyToManyField(to='comunity.CommunityUserInfo'),
        ),
        migrations.DeleteModel(
            name='CommunityGroupUserInfo',
        ),
    ]
