# Generated by Django 3.2.7 on 2022-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity', '0008_auto_20220128_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroupinfo',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
