# Generated by Django 3.2.7 on 2021-09-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcenter', '0001_initial'),
        ('labtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='medical_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='medicalcenter.medicalcentre'),
        ),
    ]
